spring.application.name=payment-ledger-wallet-system

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_ledger_db
spring.datasource.username=postgres
spring.datasource.password=ssss
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=change-this-secret-key-change-this-secret-key
app.jwt.expiration-ms=86400000

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.infotact.project1=INFO
