import { useEffect } from "react";
import { PageHeader } from "../components/PageHeader";
import { SimpleTable } from "../components/SimpleTable";
import { useTransactionStore } from "../store/transactionStore";
import { formatCurrency, formatDateTime } from "../utils/format";

export function LedgerHistoryPage() {
  const ledgerEntries = useTransactionStore((state) => state.ledgerEntries);

  useEffect(() => {
    // Call via getState() so the action reference is never a reactive dependency.
    useTransactionStore.getState().loadLedger();
  }, []);

  return (
    <div className="space-y-6" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      <PageHeader
        title="Ledger Entries"
        description="Immutable accounting lines generated by successful business transactions."
      />
      <SimpleTable
        headers={["Entry ID", "Transaction ID", "Wallet", "Type", "Amount", "Timestamp"]}
        rows={ledgerEntries.map((entry) => [
          String(entry.id),
          String(entry.transactionId),
          String(entry.walletId),
          entry.entryType,
          formatCurrency(entry.amount),
          formatDateTime(entry.createdAt),
        ])}
      />
    </div>
  );
}
