package com.infotact.project1.enums;

public enum AuditActionType {
    USER_REGISTERED,
    USER_LOGGED_IN,
    PASSWORD_CHANGED,
    DEPOSIT_SUCCESS,
    WITHDRAW_SUCCESS,
    TRANSFER_SUCCESS,
    TRANSACTION_FAILED,
    WALLET_FROZEN,
    WALLET_ACTIVATED,
    WALLET_LOCKED,
    WALLET_UNLOCKED,
    DUPLICATE_REQUEST_REJECTED
}
